version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: app-base
      POSTGRES_USER: base@user
      POSTGRES_PASSWORD: password@base123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: